const Order = [{
    id:1,
    category:"veg",
    name:"paneer masala",
    img:"https://th.bing.com/th/id/OIP._7um9ZImKRYni5MzdRnOwQHaLF?w=182&h=272&c=7&r=0&o=5&dpr=1.25&pid=1.7",
    price:450,
    cuisine_category:"indian",
    desciption:"paneer with authentic tomato cashew curry",
    cuisine_type:["dinner","lunch"],
    rating:4.5,
    quantity:1,
    menu_categ:"main course",
    add:"+Add",
    logocateg:"veg"
    },
    {   
         id:2,
        category:"veg",
        name:"paneer burji",
        img:"https://th.bing.com/th/id/OIP.0xMb4hnSls6S9uwl2e-URQHaHa?w=197&h=197&c=7&r=0&o=5&dpr=1.25&pid=1.7",
        price:350,
        cuisine_category:"indian",
        desciption:"paneer with lots of butter and vegetables",
        cuisine_type:["dinner","snacks","breakfast"],
        rating:4.5,
        quantity:1 ,
        menu_categ:"main course",
        add:"+Add",
        logocateg:"veg"
    },
    {   
        id:3,
        category:"sea food",
        name:"crab",
        img:"https://th.bing.com/th/id/OIP.pz36ABBMJ9O3lHdf9fDLQQHaE9?w=237&h=180&c=7&r=0&o=5&dpr=1.25&pid=1.7",
        price:350,
        cuisine_category:"sea food",
        desciption:"authentic sea food with gravy and additional flavour",
        cuisine_type:["dinner","lunch","snacks"],
        rating:4.5,
        quantity:1  ,
        menu_categ:"sea food",
        add:"+Add",
        logocateg:"non-veg"
    },
    {
        id:4,
        category:"contains egg",
        name:"butter omelette",
        img:"https://th.bing.com/th/id/OIP.Ap_ilZUZDdnnglNVDwFFfQHaE7?w=290&h=193&c=7&r=0&o=5&dpr=1.25&pid=1.7",
        price:200,
        cuisine_category:"indian",
        desciption:"omlette with buttur and curry",
        cuisine_type:["breakfast"],
        rating:5,
        quantity:1 ,
        menu_categ:"snacks",
        add:"+Add",
        logocateg:"egg"
    },
    {
        id:5,
        category:"non-veg",
        name:"chicken masala",
        img:"https://th.bing.com/th/id/OIP.v4Iu-X-dxcnKhatXTXP5fgHaHa?w=217&h=217&c=7&r=0&o=5&dpr=1.25&pid=1.7",
        price:550,
        cuisine_category:"mughalai",
        desciption:"chicken masala curry with authentic flavour",
        cuisine_type:["dinner","lunch"],
        rating:5,
        quantity:1 ,
        menu_categ:"main course",
        add:"+Add",
        logocateg:"nonveg"
    },
    {
        id:6,
        category:"desert",
        name:"gajar halwa",
        img:"https://th.bing.com/th/id/OIP.goOxgwnFSs2QH_UJ_v_MhgHaHw?w=199&h=208&c=7&r=0&o=5&dpr=1.25&pid=1.7",
        price:150,
        cuisine_category:"indian",
        desciption:"hot gajar halwa made in pure desi ghee",
        cuisine_type:["dinner","lunch"],
        rating:4.5,
        quantity:1,
        menu_categ:"dessert",
        add:"+Add",
        logocateg:"veg" 
    },
    {
        id:7,
        category:"beverages",
        name:"tandoori chai",
        img:"https://th.bing.com/th/id/OIP.sItoJRH4jho_SL3wCIJL4wHaJQ?w=149&h=186&c=7&r=0&o=5&dpr=1.25&pid=1.7",
        price:100,
        cuisine_category:"indian",
        desciption:"hot chai boiled in tandoor",
        cuisine_type:["breakfast","snacks"],
        rating:4.5,
        quantity:1 ,
        menu_categ:"beverages",
        add:"+Add" ,
        logocateg:"veg"
    },
    {
        id:8,
        category:"snacks",
        name:"farmhouse pizza",
        img:"https://th.bing.com/th/id/OIP.DkF99jZq23UEXUfDh994fAHaGK?w=207&h=180&c=7&r=0&o=5&dpr=1.25&pid=1.7",
        price:500, 
        cuisine_category:"italian",
        desciption:"medium pizza with 6 vegetable toppins and panner",
        cuisine_type:["snacks"],
        rating:4,
        quantity:1 ,
        menu_categ:"snacks",
        add:"+Add",
        logocateg:"veg"
    },
    {
        id:9,
        img:"https://www.sanjeevkapoor.com/UploadFiles/RecipeImages/Dal-Makhani-KhaanaKhazana.jpg",
        name:"dal makhni",
        price:250,
        cuisine_category:"indian",
        desciption:"spicy lentil preparation is made a mix of rajma and whole black gram ",
        cuisine_type:["dinner","lunch","punjabi"],
        rating:4,
        quantity:1 ,
        menu_categ:"main course",
        add:"+Add",
        logocateg:"veg"

    },
    {
        id:10,
        img:"https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/akajgetevooghwtznw56",
        name:"dosa",
        price:300,
        cuisine_category:"south indian",
        desciption:" a thin and crispy crepe made from rice and urad dal ",
        cuisine_type:["breakfast","south indian","bestseller"],
        rating:5,
        quantity:1 ,
        menu_categ:"south indian",
        add:"+Add",
        logocateg:"veg"
    }
]

export default Order;